name: tobias_no_utdid
description: A Flutter plugin for allowing users to authenticate or pay with native Android&iOS AliPay SDKs.
version: 2.4.1+1
homepage: https://github.com/zenganiu/tobias_no_utdid

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.jarvan.tobias
        pluginClass: TobiasPlugin
      ios:
        pluginClass: TobiasPlugin

